- name: Configure tmpreaper
  template: src=tmpreaper.conf.j2 dest=/etc/tmpreaper.conf
  tags: system

- name: Copy SSL-Files
  copy: src=$item dest=/etc/ssl/ owner=root group=ssl-cert mode=0640
  with_fileglob: ./ssl/$inventory_hostname/*
  tags: ssl
